# -*- coding: utf-8 -*-
"""PoissonRVPMF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gvNoXVFN2Tt_fGkPANcY5ve0OY53BQep
"""

"""
Assignment1
Enrollement No. : MT21MCS013 Jay
"""
from scipy.stats import poisson
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(1, 1)

mu = 0.6

x = np.arange(poisson.ppf(0.01, mu),
              poisson.ppf(0.99, mu))

rv = poisson(mu)
ax.bar(x, rv.pmf(x),label="Poission PMF")
ax.legend(loc='best', frameon=False)
plt.show()