# -*- coding: utf-8 -*-
"""ConstantRVPMF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16DDorx3OpIAH632i60wUqel93Hq7d20S
"""

"""
Assignment1
Enrollement No. : MT21MCS013 Jay
"""
import matplotlib.pyplot as plt
def plotBarChat(xAxis,yAxis):
  fig = plt.figure()
  ax = fig.add_axes([0,0,1,1])
  
  ax.bar(xAxis,yAxis)
  plt.show()
'''
1 if x =3 
0 other wise
'''
def plot_constantRv_pmf(x_values_list):
  pmf_list=[]
  for value in x_values_list:
    if value!=3:
      pmf_list.append(0)
    else:
      pmf_list.append(1)
      
  plotBarChat(x_values_list,pmf_list)
plot_constantRv_pmf([4,5,3,1,3,6,9,11])

