# -*- coding: utf-8 -*-
"""UniformRVPMF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lkVpT4R7sjS4SVabH9zSxMEi8xZWoU_2
"""

"""
Assignment1
Enrollement No. : MT21MCS013 Jay
"""
from scipy.stats import uniform
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(1, 1)

x = np.linspace(uniform.ppf(0.01),
                uniform.ppf(0.99), 100)

rv = uniform()
ax.bar(x, rv.pdf(x),label='Uniform PMF')
ax.legend(loc='best', frameon=False)
plt.show()