# -*- coding: utf-8 -*-
"""GeomatricRVPMF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uwfVEES6JzlxHKQNd5UWl7rkD02udFVN
"""

"""
Assignment1
Enrollement No. : MT21MCS013 Jay
"""
from scipy.stats import geom
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(1, 1)

p = 0.5

x = np.arange(geom.ppf(0.01, p),
              geom.ppf(0.99, p))

rv = geom(p)
ax.bar(x,rv.pmf(x),label='Geomatric PMF')
ax.legend(loc='best', frameon=False)
plt.show()