# -*- coding: utf-8 -*-
"""BinomialRVPMF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_-eXKrfto9sHcsg04MvMJwtzmh-Q8mvk
"""

"""
Assignment1
Enrollement No. : MT21MCS013 Jay
"""
from scipy.stats import binom
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(1, 1)
n, p = 5, 0.4

x = np.arange(binom.ppf(0.01, n, p),
              binom.ppf(0.99, n, p))
rv = binom(n, p)
ax.bar(x, rv.pmf(x),label="Binomial PMF")
ax.legend(loc='best', frameon=False)
plt.show()