# -*- coding: utf-8 -*-
"""CentralLimitTheoremUniformRV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rfem452xWVN9p0itLBADDwrxsvdTnfPX
"""

"""
Enrollement No. : MT21MCS013 Jay
"""
import numpy as np
import seaborn as sns
import statistics as stat

def sample_mean_calculator(population_array, sample_size, n_samples):
  sample_means = []
  for i in range(n_samples):
    sample = np.random.choice(population_array, size=sample_size, replace=False)
    sample_mean = stat.mean(sample)
    sample_means.append(sample_mean)
  return sample_means


u = np.random.uniform(size=10000)
_ = sns.distplot(sample_mean_calculator(u, 1000, 1000),kde=False)

